Controllers/PlanController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TalentHunt.Models;
using TalentHunt.ModelView;

namespace TalentHunt.Controllers
{
    public class PlanController : Controller
    {
        private huntdbEntities1 db = new huntdbEntities1();

        // GET: Plan
        public ActionResult Index()
        {
            if(Session["aid"]!=null)
            {
                return View(db.plans.ToList());
            }
            else
            {
                return RedirectToAction("Login", "AdminLogin");
            }
            
        }

        public ActionResult planselect()
        {
            return View(db.plans.ToList());
        }

        public ActionResult upgradeplan()
        {
            return View(db.plans.ToList());
        }

        [HttpPost]

        public ActionResult Index(string Search)
        {
            if (Session["aid"] != null)
            {
                if (Search == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                if (Search.ToLower() == "all" || Search == "")
                {
                    return View(db.plans.ToList());
                }
                List<plan> planTS = db.plans.Where(p => p.plantype.Contains(Search)).ToList();
                if (planTS.Count() == 0)
                {
                    try
                    {
                        int s = Convert.ToInt32(Search);
                        List<plan> planLnS = db.plans.Where(p => p.price <= s).ToList();
                        if (planLnS.Count() == 0)
                        {
                            TempData["pNotFound"] = "Plan Not Found";
                        }
                        else
                        {
                            return View(planLnS.ToList());
                        }
                    }
                    catch
                    {
                        TempData["pNotFound"] = "Plan Not Found";

                    }
                }
                else
                {
                    return View(planTS.ToList());
                }

                return View(planTS.ToList());
            }
            else
            {
                return RedirectToAction("Login", "AdminLogin");
            }
        }

        // GET: Plan/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            plan plan = db.plans.Find(id);
            if (plan == null)
            {
                return HttpNotFound();
            }
            return View(plan);
        }

        // GET: Plan/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Plan/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "planid,plantype,duration,price,maxevents,maxbids,description,benefits")] planv planv)
        {
            if (ModelState.IsValid)
            {
                plan plan = new plan();
                AutoMapper.Mapper.Map(planv, plan);
                db.plans.Add(plan);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(planv);
        }

        // GET: Plan/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            plan plan = db.plans.Find(id);
            planv planv = new planv();
            AutoMapper.Mapper.Map(plan, planv);
            if (plan == null)
            {
                return HttpNotFound();
            }
            return View(planv);
        }

        // POST: Plan/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "planid,plantype,duration,price,maxevents,maxbids,description,benefits")] planv planv)
        {
            if (ModelState.IsValid)
            {
                plan plan = new plan();
                AutoMapper.Mapper.Map(planv, plan);

                db.Entry(plan).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(planv);
        }

        // GET: Plan/Delete/5
        public ActionResult Delete(int? id)
        {
            if (Session["aid"] != null)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                plan plan= db.plans.Find(id);
                if (plan != null)
                {
                    db.plans.Remove(plan);
                    try
                    {
                        db.SaveChanges();
                    }
                    catch (Exception e)
                    {
                        TempData["planerr"] = "Plan cannot be deleted because users are subscribed to this plan";
                    }
                    return RedirectToAction("Index");
                }
                else
                {
                    return HttpNotFound();
                }
            }
            else
            {
                return RedirectToAction("Login", "AdminLogin");
            }
        }

        // POST: Plan/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            plan plan = db.plans.Find(id);
            db.plans.Remove(plan);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TalentHunt.Models;
using TalentHunt.ModelView;
using System.IO;

namespace TalentHunt.Controllers
{
    public class UserController : Controller
    {
        private huntdbEntities1 db = new huntdbEntities1();

        // GET: User
        public ActionResult Index()
        {
            var talents = db.talents.ToList();
            TempData["talents"] = talents;
            return View(db.userprofiles.ToList());
        }
        [HttpPost]

        public ActionResult Index(int tid)
        {
            if (Session["pid"] != null)
            {
                if(tid.Equals(null)|| tid == 0)
                {
                    var talent = db.talents.ToList();
                    TempData["talents"] = talent;
                    return View(db.userprofiles.ToList());
                }
                List<userprofile> plan = db.userprofiles.Where(p => p.tid.Equals(tid)).ToList();
                if (plan.Count() == 0)
                {
                    TempData["NotFound"] = "No such talent found";
                }
                var talents = db.talents.ToList();
                TempData["talents"] = talents;
                return View(plan.ToList());
            }
            else
            {
                return RedirectToAction("Login", "User");
            }
        }

        public ActionResult Login()
        {
            return View();
        }

        public String talentlist()
        {
            string output = "Testing";
            return output;
        }

        public ActionResult UserView()
        {
            if (Session["aid"] != null)
            {
                return View(db.users.ToList());
            }
            else
            {
                return RedirectToAction("Login", "AdminLogin");
            }

        }
        [HttpPost]
        public ActionResult UserView(string Search)
        {
            if (Session["aid"] != null)
            {
                if (Search == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                if (Search.ToLower() == "all" || Search == "")
                {
                    return View(db.users.ToList());
                }
                List<user> users= db.users.Where(p => p.fname.Contains(Search) || Search == null).ToList();
                if (users.Count() == 0)
                {
                    List<user> userg = db.users.Where(p => p.gender.Equals(Search)).ToList();
                    if(userg.Count() ==0)
                    {
                        try
                        {
                            int s = Convert.ToInt32(Search);
                            List<user> ages = db.users.Where(p => p.age <= s).ToList();
                            if (ages.Count() == 0)
                            {
                                TempData["NotFound"] = "User Not Found";
                            }
                            else
                            {
                                return View(ages.ToList());
                            }
                        }
                        catch
                        {
                            TempData["NotFound"] = "User Not Found";
                        }
                    }
                    else
                    {
                        return View(userg.ToList());
                    }
                    
                    
                }
                else
                {
                    return View(users.ToList());
                }

                return View(users.ToList());
            }
            else
            {
                return RedirectToAction("Login", "AdminLogin");
            }
        }
        public ActionResult ShortView(int? id, user users, talent talents, userprofile userprofiles, image images)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (Session["aid"] != null)
            {
                int usrid = Convert.ToInt32(id);
                var result = db.userprofiles.Where(p => p.userid.Equals(usrid));
                TempData["talentlists"] = result;

                var elists = db.images.Where(p => p.userid.Equals(usrid));
                TempData["piclists"] = elists;

                var videolists = db.videos.Where(p => p.userid.Equals(usrid));
                TempData["videolists"] = videolists;

                var rates = db.ratings.Where(p => p.userid.Equals(usrid));
                if (rates.Count() != 0)
                {
                    double sum = 0;
                    double finalrate = 0;
                    double total = rates.Count();
                    foreach (var rt in rates)
                    {
                        sum += rt.rating1;
                    }
                    finalrate = sum / total;
                    TempData["ratings"] = finalrate;
                }
                else
                {
                    TempData["ratings"] = 0;
                }

                user user = db.users.Find(id);
                if (user == null)
                {
                    return HttpNotFound();
                }
                return View(user);
            }
            else
            {
                return RedirectToAction("AdminLogin", "Admin");
            }
                
        }

        public ActionResult Profile(user users,talent talents,userprofile userprofiles,image images)
        {
            if(Session["uid"]!=null)
            {

                int usrid = Convert.ToInt32(HttpContext.Session["uid"]);
                var result = db.userprofiles.Where(p => p.userid.Equals(usrid));
                TempData["talentlists"] = result;

                var elists = db.images.Where(p => p.userid.Equals(usrid));
                TempData["piclists"] = elists;

                var videolists = db.videos.Where(p => p.userid.Equals(usrid));
                TempData["videolists"] = videolists;

                var rates = db.ratings.Where(p => p.userid.Equals(usrid));
                if(rates.Count()!=0)
                {
                    double sum = 0;
                    double finalrate = 0;
                    double total = rates.Count();
                    foreach (var rt in rates)
                    {
                        sum += rt.rating1;
                    }
                    finalrate = sum / total;
                    TempData["ratings"] = finalrate;
                }   
                else
                {
                    TempData["ratings"] = 0;
                }

                var usr = db.users.Where(p => p.userid.Equals(usrid)).FirstOrDefault();
                if (result!=null)
                {
                    TempData["fname"] = usr.fname.ToString();
                    TempData["lname"] = usr.lname.ToString();
                    TempData["age"] = usr.age.ToString();
                    TempData["gender"] = usr.gender.ToString();
                    TempData["mail"] = usr.email.ToString();
                }
                return View(db.users.ToList());


            }
            else
            {
                return RedirectToAction("Login","User");
            }
        }

        [HttpPost]

        public ActionResult Login(login login, string options)
        {

            if (options == "user")
            {
                user usr = db.users.Where(p => p.username.Equals(login.username) && p.password.Equals(login.password)).FirstOrDefault();
                if (usr != null)
                {
                   if(usr.status=="active")
                    {
                        Session["uid"] = usr.userid.ToString();
                        Session["photo"] = usr.photo.ToString();
                        Session["uname"] = usr.fname.ToString() + " " + usr.lname.ToString();
                        TempData["gender"] = usr.gender;
                        TempData["age"] = usr.age;
                        return RedirectToAction("Profile");
                    }
                   else
                    {
                        ViewBag.err = "You are banned from using TalentHunt";
                    }
                }
                else
                {
                    ViewBag.err = "Invalid User Credentials";
                    TempData["register"] = "<div class='font-16 weight-600 pt-10 pb-10 text-center' data-color='#707373'>OR</div><div class='input-group mb-0'><a class='btn btn-outline-primary btn-lg btn-block' href='/User/Create'>Register To Create User Account</a></div>";
                }
            }
            else if (options == "production")
            {
                production pro = db.productions.Where(p => p.username.Equals(login.username) && p.password.Equals(login.password)).FirstOrDefault();
                if (pro != null)
                {
                    if(pro.status=="active")
                    {
                        Session["pid"] = pro.pid.ToString();
                        Session["pimage"] = pro.pimage.ToString();
                        Session["pname"] = pro.pname.ToString();
                        return RedirectToAction("Proinfo", "Production");
                    }
                    else
                    {
                        ViewBag.err = "You are banned from using TalentHunt";
                    }
                }
                else
                {
                    ViewBag.err = "Invalid Production Credentials";

Views/User/Delete.cshtml
@model TalentHunt.Models.user

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>user</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.fname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.lname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.lname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.age)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.age)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.city)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.city)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.state)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.state)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.pincode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.pincode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.photo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.photo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.username)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.username)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.password)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/User/Index.cshtml
@model IEnumerable<TalentHunt.Models.userprofile>
@using TalentHunt.Models

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <!-- Basic Page Info -->
    <meta charset="utf-8">
    <title>TalentHunt</title>

    <!-- Site favicon -->
    <link rel="apple-touch-icon" sizes="180x180" href="~/vendors/images/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="~/vendors/images/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="~/vendors/images/favicon-16x16.png">

    <!-- Mobile Specific Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap" rel="stylesheet">
    <!-- CSS -->
    <link rel="stylesheet" type="text/css" href="~/vendors/styles/core.css">
    <link rel="stylesheet" type="text/css" href="~/vendors/styles/icon-font.min.css">
    <link rel="stylesheet" type="text/css" href="~/vendors/styles/style.css">

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-119386393-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag() { dataLayer.push(arguments); }
        gtag('js', new Date());

        gtag('config', 'UA-119386393-1');
    </script>


    <!-- Favicon icon -->
    <link rel="icon" href="~/assets/images/favicon.svg" type="image/x-icon">
    <!-- fontawesome icon -->
    <link rel="stylesheet" href="~/assets/fonts/fontawesome/css/fontawesome-all.min.css">
    <!-- animation css -->
    <link rel="stylesheet" href="~/assets/plugins/animation/css/animate.min.css">

    <!-- vendor css -->
    <link rel="stylesheet" href="~/assets/css/style.css">
</head>

<body>
    @{
        Html.RenderPartial("__Navbar");
    }

    <div class="my-3">
        <center>
            <h1 class="h1 text-blue">Talents</h1><br />
            @using (Html.BeginForm(FormMethod.Post))
            {
                <center>
                <div class="mx-0 d-inline-flex" style="max-width:800px">
                    <select class="form-control" id="tid" name="tid">
                        <option selected="selected" value="0">-- Select Talent --</option>
                        @foreach (var data in (IEnumerable<talent>)TempData["talents"])
                        {
                            <option value="@data.tid">@Html.DisplayFor(modelItem => data.ttype)</option>
                        }
                    </select>
                        <input type="submit" class="btn btn-outline-primary mx-2" value="Search" name="submit" />
                </div>
                </center>
             }
        <br /><br />

            <center>
                <p style="color:indianred">@TempData["NotFound"]</p>
            </center>
        <div class="mb-20 ">
            @foreach (var item in Model)
            {
                <div class="card mx-2 d-inline-flex" style="width: 18rem;">
                    <img class="card-img-top" src="@Url.Content(item.user.photo)" alt="Card image cap">
                    <div class="card-body">
                        <p class="card-text"><strong>@Html.DisplayFor(modelItem => item.user.fname)  @Html.DisplayFor(modelItem => item.user.lname)</strong></p>
                        <p class="card-text">@Html.DisplayFor(modelItem => item.user.gender) | @Html.DisplayFor(modelItem => item.user.age)</p>
                        <p class="card-text" style="color:indianred">@Html.DisplayFor(modelItem => item.talent.ttype)</p>
                    </div>
                    @Html.ActionLink("View Talent", "Details", "User", new { id = item.userid }, new { @class = "btn btn-outline-primary my-3 mx-2" })
                </div>
            }
        </div>
</center>
    </div>





    <!-- js -->
    <script src="~/vendors/scripts/core.js"></script>
    <script src="~/vendors/scripts/script.min.js"></script>
    <script src="~/vendors/scripts/process.js"></script>
    <script src="~/vendors/scripts/layout-settings.js"></script>

</body>
</html>

Views/User/Login.cshtml
@model TalentHunt.ModelView.login

@{ ViewBag.Title = "Login";
                Layout = null; }



<!DOCTYPE html>
<html>
<head>
    <!-- Basic Page Info -->
    <meta charset="utf-8">
    <title>TalentHunt</title>

    <!-- Site favicon -->
    <link rel="apple-touch-icon" sizes="180x180" href="~/vendors/images/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="~/vendors/images/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="~/vendors/images/favicon-16x16.png">

    <!-- Mobile Specific Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap" rel="stylesheet">
    <!-- CSS -->
    <link rel="stylesheet" type="text/css" href="~/vendors/styles/core.css">
    <link rel="stylesheet" type="text/css" href="~/vendors/styles/icon-font.min.css">
    <link rel="stylesheet" type="text/css" href="~/vendors/styles/style.css">
    <style>
        /* Style The Dropdown Button */
        .dropbtn {
            background-color: #fff;
            color: blue;
            padding: 10px;
            font-size: 25px;
            font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }

        /* The container <div> - needed to position the dropdown content */
        .dropdown {
            position: inherit;
            display: inline-block;
            margin-right: 50px;
        }

        /* Dropdown Content (Hidden by Default) */
        .dropdown-content {
            display: none;
            position: absolute;
            background-color: #f9f9f9;
            text-align: center;
            border-radius: 10px;
            min-width: 160px;
            box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
            z-index: 1;
        }

            /* Links inside the dropdown */
            .dropdown-content a {
                color: black;
                padding: 12px 6px;
                text-decoration: none;
                display: block;
            }

                /* Change color of dropdown links on hover */
                .dropdown-content a:hover {
                    background-color: #fff
                }

        /* Show the dropdown menu on hover */
        .dropdown:hover .dropdown-content {
            display: block;
        }

        /* Change the background color of the dropdown button when the dropdown content is shown */
        .dropdown:hover .dropbtn {
            background-color: #fff;
        }
    </style>
</head>
<body class="login-page">
    <div class="login-header box-shadow">
        <div class="container-fluid d-flex justify-content-between align-items-center">
            <div class="brand-logo">
                <a href="@Url.Action("Index","Home")">
                    <img src="~/vendors/images/logo1.png" height="145" width="145" alt="Logo">
                </a>
            </div>
            <div class="login-menu">
                <div class="dropdown">
                    <button class="dropbtn">Register</button>
                    <div class="dropdown-content">
                        <a href="@Url.Action("Create")">User</a>
                        <a href="@Url.Action("planselect","Plan")">Production</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="login-wrap d-flex align-items-center flex-wrap justify-content-center">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-md-6 col-lg-7">
                    <img src="~/vendors/images/login-page-img.png" alt="">
                </div>
                <div class="col-md-6 col-lg-5">
                    <div class="login-box bg-white box-shadow border-radius-10">
                        <div class="login-title">
                            <h2 class="text-center text-primary">Login to Talent Hunt</h2>
                        </div>
                        @using (Html.BeginForm("Login", "User", FormMethod.Post))
                        {
                            @Html.AntiForgeryToken()
                            <div class="select-role">
                                <div class="btn-group btn-group-toggle" data-toggle="buttons">
                                    <label class="btn">
                                        <input type="radio" name="options" id="user" value="user">
                                        <div class="icon"><img src="~/vendors/images/person.svg" class="svg"></div>
                                        <span>I'm</span>
                                        Expert
                                    </label>
                                    <label class="btn">
                                        <input type="radio" name="options" id="production" value="production">
                                        <div class="icon"><img src="~/vendors/images/briefcase.svg" class="svg"></div>
                                        <span>I'm</span>
                                        Production
                                    </label>
                                </div>
                            </div>
                             
                            @Html.ValidationMessageFor(model => model.username, "", new { @class = "text-danger" })
                            <div class="input-group custom">
                                @Html.EditorFor(model => model.username, new { htmlAttributes = new { @class = "form-control", placeholder = "Enter UserName", @value = ViewBag.uUsername } })
                                <div class="input-group-append custom">
                                <span class="input-group-text"><i class="icon-copy dw dw-user1"></i></span>
                                </div>
                            </div>
                            
                            @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
                            <div class="input-group custom">
                                 @Html.EditorFor(model => model.password, new { htmlAttributes = new { @class = "form-control", placeholder = "Enter Password", @value = ViewBag.uPassword } })
                                <div class="input-group-append custom">
                                     <span class="input-group-text"><i class="dw dw-padlock1"></i></span>
                                 </div>
                            </div>
                            <span class="text-danger">@ViewBag.err</span>
                            <span class="text-danger">@ViewBag.select</span>

                            <div class="row">
                                <div class="col-sm-12">
                                    <div class="input-group mb-0">
                                        <button type="submit" class="btn btn-primary btn-lg btn-block">Login</button>
                                        @*<input class="btn btn-primary btn-lg btn-block" type="submit" />*@
                                    </div>
                                    @Html.Raw(TempData["Register"])
                                </div>
                            </div>
                         }
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- js -->
    <script src="~/vendors/scripts/core.js"></script>
    <script src="~/vendors/scripts/script.min.js"></script>
    <script src="~/vendors/scripts/process.js"></script>
    <script src="~/vendors/scripts/layout-settings.js"></script>
</body>
</html>