Models/video.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TalentHunt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class video
    {
        public int vid { get; set; }
        public int userid { get; set; }
        public int tid { get; set; }
        public string video1 { get; set; }
        public string caption { get; set; }
    
        public virtual talent talent { get; set; }
        public virtual user user { get; set; }
    }
}

Controllers/VideosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TalentHunt.Models;
using TalentHunt.ModelView;

namespace TalentHunt.Controllers
{
    public class VideosController : Controller
    {
        private huntdbEntities1 db = new huntdbEntities1();

        // GET: Videos
        public ActionResult Index()
        {
            var videos = db.videos.Include(v => v.talent).Include(v => v.user);
            return View(videos.ToList());
        }

        // GET: Videos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            video video = db.videos.Find(id);
            if (video == null)
            {
                return HttpNotFound();
            }
            return View(video);
        }

        // GET: Videos/Create
        public ActionResult Create(int? id)
        {
            ViewBag.uid = id;
            int usrid = Convert.ToInt32(id);
            ViewBag.tid = new SelectList(db.talents, "tid", "ttype");
            var talents = db.talents.ToList();
            var finallist = db.userprofiles.Where(p => p.userid.Equals(usrid));

            TempData["talents"] = finallist;
            ViewBag.userid = new SelectList(db.users, "userid", "fname");
            return View();
        }

        // POST: Videos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "vid,userid,tid,video1,caption,VideoFile")] videov videov,int uid)
        {
            if (ModelState.IsValid)
            {
                if (videov.tid == 0 && videov.VideoFile == null)
                {
                    ViewBag.tiderr = "*";
                    ViewBag.emptyerr = "*";
                }
                else
                {
                    if (videov.tid == 0)
                    {
                        ViewBag.tiderr = "*";
                    }
                    else
                    {
                        if (videov.VideoFile == null)
                        {
                            ViewBag.emptyerr = "*";
                        }
                        else if (videov.VideoFile.ContentType == "video/mp4")
                        {
                            string fileName = Path.GetFileNameWithoutExtension(videov.VideoFile.FileName);
                            string extension = Path.GetExtension(videov.VideoFile.FileName);
                            fileName = fileName + extension;
                            videov.video1 = "~/Videos/" + fileName;
                            fileName = Path.Combine(Server.MapPath("~/Videos"), fileName);
                            videov.VideoFile.SaveAs(fileName);

                            videov.userid = uid;

                            video video = new video();
                            AutoMapper.Mapper.Map(videov, video);

                            db.videos.Add(video);
                            db.SaveChanges();
                            return RedirectToAction("Profile", "User");
                        }
                        else
                        {
                            ViewBag.mp4err = "Must be mp4";
                        }

                    }
                }
            }

            ViewBag.tid = new SelectList(db.talents, "tid", "ttype", videov.tid);
            ViewBag.uid = uid;
            int usrid = Convert.ToInt32(uid);
            var talents = db.talents.ToList();
            var finallist = db.userprofiles.Where(p => p.userid.Equals(usrid));
            TempData["talents"] = finallist;
            return View(videov);
        }
    

        // GET: Videos/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            video video = db.videos.Find(id);
            videov videov = new videov();
            AutoMapper.Mapper.Map(video, videov);
            if (video == null)
            {
                return HttpNotFound();
            }
            ViewBag.tid = new SelectList(db.talents, "tid", "ttype", videov.tid);
            ViewBag.userid = new SelectList(db.users, "userid", "fname", videov.userid);
            return View(videov);
        }

        // POST: Videos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "vid,userid,tid,video1,caption")] videov videov)
        {
            if (ModelState.IsValid)
            {
                video video = new video();
                AutoMapper.Mapper.Map(videov, video);
                db.Entry(video).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.tid = new SelectList(db.talents, "tid", "ttype", videov.tid);
            ViewBag.userid = new SelectList(db.users, "userid", "fname", videov.userid);
            return View(videov);
        }

        // GET: Videos/Delete/5
        public ActionResult Delete(int? id)
        {
            if (Session["uid"] != null)
            {
                if (id == null)
                {
                    return RedirectToAction("Profile", "User");
                }
                video video = db.videos.Find(id);
                if (video != null)
                {
                    db.videos.Remove(video);
                    db.SaveChanges();
                    return RedirectToAction("Profile", "User");
                }
                else
                {
                    return RedirectToAction("Profile", "User");
                }
            }
            else
            {
                return RedirectToAction("Login", "User");
            }
        }

        // POST: Videos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            video video = db.videos.Find(id);
            db.videos.Remove(video);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Videos/Create.cshtml
@model TalentHunt.ModelView.videov
@using TalentHunt.Models
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <!-- Basic Page Info -->
    <meta charset="utf-8">
    <title>TalentHunt</title>

    <!-- Site favicon -->
    <link rel="apple-touch-icon" sizes="180x180" href="~/vendors/images/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="~/vendors/images/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="~/vendors/images/favicon-16x16.png">

    <!-- Mobile Specific Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap" rel="stylesheet">
    <!-- CSS -->
    <link rel="stylesheet" type="text/css" href="~/vendors/styles/core.css">
    <link rel="stylesheet" type="text/css" href="~/vendors/styles/icon-font.min.css">
    <link rel="stylesheet" type="text/css" href="~/vendors/styles/style.css">

    <!-- Favicon icon -->
    <link rel="icon" href="~/assets/images/favicon.svg" type="image/x-icon">
    <!-- fontawesome icon -->
    <link rel="stylesheet" href="~/assets/fonts/fontawesome/css/fontawesome-all.min.css">
    <!-- animation css -->
    <link rel="stylesheet" href="~/assets/plugins/animation/css/animate.min.css">

    <!-- vendor css -->
    <link rel="stylesheet" href="~/assets/css/style.css">


    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-119386393-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag() { dataLayer.push(arguments); }
        gtag('js', new Date());

        gtag('config', 'UA-119386393-1');
    </script>
</head>
<body>

    @{
        Html.RenderPartial("__Navbar");
    }

    <div class="main-container">
        <div class="pd-tr-20 xs-pd-10-10">
            <div class="min-height-200px">
                <!-- Default Basic Forms Start -->
                <div class="pd-20 card-box mb-30">
                    <div class="clearfix">
                        <div class="pull-left">
                            <h4 class="text-blue h4">Add Video</h4>
                            <hr style="color:darkblue" />
                        </div>
                    </div>
                    @using (Html.BeginForm("Create", "Videos", FormMethod.Post, new { enctype = "multipart/form-data" }))
                    {
                        @Html.AntiForgeryToken()
                        @Html.Hidden("uid", (object)ViewBag.uid)

                        <div class="form-group row">
                            <label class="col-sm-12 col-md-2 col-form-label">Talent</label>
                            <div class="col-sm-12 col-md-10">
                                <select class="form-control" id="tid" name="tid">
                                    <option selected="selected" value="0">-- Select Talent --</option>
                                    @foreach (var data in (IEnumerable<userprofile>)TempData["talents"])
                                    {
                                         <option value="@data.talent.tid">@Html.DisplayFor(modelItem => data.talent.ttype)</option>
                                    }
                                </select>
                                <span class="text-danger">@ViewBag.tiderr</span>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-sm-12 col-md-2 col-form-label">Video</label>
                            <div class="col-md-10">
                                <input type="file" name="VideoFile" class="form-control" multiple="multiple" />
                                <span class="text-danger">@ViewBag.emptyerr</span>
                                <span class="text-danger">@ViewBag.mp4err</span>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-sm-12 col-md-2 col-form-label">Caption</label>
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.caption, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.caption, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <center>
                            <input type="submit" value="Submit" class=" btn btn-primary" />
                        </center>

                    }
                </div>
            </div>
        </div>
    </div>

    <!-- js -->
    <script src="~/vendors/scripts/core.js"></script>
    <script src="~/vendors/scripts/script.min.js"></script>
    <script src="~/vendors/scripts/process.js"></script>
    <script src="~/vendors/scripts/layout-settings.js"></script>
</body>
</html>

Views/Videos/Delete.cshtml
@model TalentHunt.Models.video

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>TalentHunt</title>
</head>
<body>
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>video</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.video1)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.video1)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.caption)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.caption)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.talent.ttype)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.talent.ttype)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.user.fname)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.user.fname)
            </dd>
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</body>
</html>

Views/Videos/Details.cshtml
@model TalentHunt.Models.video

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>TalentHunt</title>
</head>
<body>
    <div>
        <h4>video</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.video1)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.video1)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.caption)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.caption)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.talent.ttype)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.talent.ttype)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.user.fname)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.user.fname)
            </dd>
    
        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.vid }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</body>
</html>

Views/Videos/Edit.cshtml
@model TalentHunt.ModelView.videov

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>TalentHunt</title>
</head>
<body>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>video</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.vid)
    
            <div class="form-group">
                @Html.LabelFor(model => model.userid, "userid", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("userid", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.userid, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.tid, "tid", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("tid", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.tid, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.video1, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.video1, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.video1, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.caption, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.caption, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.caption, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

Views/Videos/Index.cshtml
@model IEnumerable<TalentHunt.Models.video>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>TalentHunt</title>
</head>
<body>
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.video1)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.caption)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.talent.ttype)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.user.fname)
            </th>
            <th></th>
        </tr>
    
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.video1)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.caption)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.talent.ttype)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.user.fname)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.vid }) |
                @Html.ActionLink("Details", "Details", new { id=item.vid }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.vid })
            </td>
        </tr>
    }
    
    </table>
</body>
</html>