Models/eventrequire.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TalentHunt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class eventrequire
    {
        public int erid { get; set; }
        public int pid { get; set; }
        public int peid { get; set; }
        public int tid { get; set; }
        public string agerange { get; set; }
        public string gender { get; set; }
        public string payrange { get; set; }
    
        public virtual production production { get; set; }
        public virtual talent talent { get; set; }
        public virtual productionevent productionevent { get; set; }
    }
}

Controllers/EventRequireController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TalentHunt.Models;
using TalentHunt.ModelView;

namespace TalentHunt.Controllers
{
    public class EventRequireController : Controller
    {
        private huntdbEntities1 db = new huntdbEntities1();

        // GET: EventRequire
        public ActionResult Index()
        {
            var eventrequires = db.eventrequires.Include(e => e.production).Include(e => e.productionevent).Include(e => e.talent);
            return View(eventrequires.ToList());
        }

        // GET: EventRequire/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            eventrequire eventrequire = db.eventrequires.Find(id);
            if (eventrequire == null)
            {
                return HttpNotFound();
            }
            return View(eventrequire);
        }

        // GET: EventRequire/Create
        public ActionResult Create(int? peid)
        {

            ViewBag.pid = new SelectList(db.productions, "pid", "pname");
            ViewBag.peid = peid;
            ViewBag.tid = new SelectList(db.talents, "tid", "ttype");
            return View();
        }

        // POST: EventRequire/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "erid,pid,peid,tid,agerange,gender,payrange")] eventrequirev eventrequirev,int peid)
        {
            if (ModelState.IsValid)
            {
                eventrequirev.pid = Convert.ToInt32(HttpContext.Session["pid"]);
                eventrequirev.peid = peid;

                eventrequire eventrequire = new eventrequire();
                AutoMapper.Mapper.Map(eventrequirev, eventrequire);
                db.eventrequires.Add(eventrequire);
                db.SaveChanges();
                return RedirectToAction("Index","ProductionEvent");
            }

            ViewBag.pid = new SelectList(db.productions, "pid", "pname", eventrequirev.pid);
            ViewBag.peid = new SelectList(db.productionevents, "peid", "ename", eventrequirev.peid);
            ViewBag.tid = new SelectList(db.talents, "tid", "ttype", eventrequirev.tid);
            return View(eventrequirev);
        }

        // GET: EventRequire/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            eventrequire eventrequire = db.eventrequires.Find(id);
            eventrequirev eventrequirev = new eventrequirev();
            AutoMapper.Mapper.Map(eventrequire, eventrequirev);
            if (eventrequire == null)
            {
                return HttpNotFound();
            }
            ViewBag.pid = new SelectList(db.productions, "pid", "pname", eventrequirev.pid);
            ViewBag.peid = new SelectList(db.productionevents, "peid", "ename", eventrequirev.peid);
            ViewBag.tid = new SelectList(db.talents, "tid", "ttype", eventrequirev.tid);
            return View(eventrequirev);
        }

        // POST: EventRequire/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "erid,pid,peid,tid,agerange,gender,payrange")] eventrequirev eventrequirev)
        {
            if (ModelState.IsValid)
            {
                eventrequire eventrequire = new eventrequire();
                eventrequire.erid = eventrequirev.erid;
                eventrequire.pid= eventrequirev.pid;
                eventrequire.peid = eventrequirev.peid;
                eventrequire.tid = eventrequirev.tid;
                eventrequire.agerange = eventrequirev.agerange;
                eventrequire.gender = eventrequirev.gender;
                eventrequire.payrange = eventrequirev.payrange;


                db.Entry(eventrequire).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Details","ProductionEvent",new { id=eventrequirev.peid});
            }
            ViewBag.pid = new SelectList(db.productions, "pid", "pname", eventrequirev.pid);
            ViewBag.peid = new SelectList(db.productionevents, "peid", "ename", eventrequirev.peid);
            ViewBag.tid = new SelectList(db.talents, "tid", "ttype", eventrequirev.tid);
            return View(eventrequirev);
        }

        // GET: EventRequire/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            eventrequire eventrequire = db.eventrequires.Find(id);
            if (eventrequire == null)
            {
                return HttpNotFound();
            }
            return View(eventrequire);
        }

        // POST: EventRequire/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            eventrequire eventrequire = db.eventrequires.Find(id);
            db.eventrequires.Remove(eventrequire);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/EventRequire/Create.cshtml
@model TalentHunt.ModelView.eventrequirev

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <!-- Basic Page Info -->
    <meta charset="utf-8">
    <title>TalentHunt</title>

    <!-- Site favicon -->
    <link rel="apple-touch-icon" sizes="180x180" href="~/vendors/images/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="~/vendors/images/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="~/vendors/images/favicon-16x16.png">

    <!-- Mobile Specific Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap" rel="stylesheet">
    <!-- CSS -->
    <link rel="stylesheet" type="text/css" href="~/vendors/styles/core.css">
    <link rel="stylesheet" type="text/css" href="~/vendors/styles/icon-font.min.css">
    <link rel="stylesheet" type="text/css" href="~/vendors/styles/style.css">


    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-119386393-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag() { dataLayer.push(arguments); }
        gtag('js', new Date());

        gtag('config', 'UA-119386393-1');
    </script>


    <!-- Favicon icon -->
    <link rel="icon" href="~/assets/images/favicon.svg" type="image/x-icon">
    <!-- fontawesome icon -->
    <link rel="stylesheet" href="~/assets/fonts/fontawesome/css/fontawesome-all.min.css">
    <!-- animation css -->
    <link rel="stylesheet" href="~/assets/plugins/animation/css/animate.min.css">

    <!-- vendor css -->
    <link rel="stylesheet" href="~/assets/css/style.css">
</head>
<body class="">

    @{
        Html.RenderPartial("__Navbar");
    }

    <div class="main-container">
        <div class="pd-tr-20 xs-pd-10-10">
            <div class="min-height-200px">
                <!-- Default Basic Forms Start -->
                <div class="pd-20 card-box mb-30">
                    <div class="clearfix">
                        <div class="pull-left">
                            <h4 class="text-blue h4">Add Event Requirements</h4>
                            <hr style="color:darkblue" />
                        </div>
                    </div>
                    @using (Html.BeginForm("Create", "EventRequire", FormMethod.Post, new { enctype = "multipart/form-data" }))
                    {
                        @Html.AntiForgeryToken()
                        @Html.Hidden("peid", (object)ViewBag.peid)

                        <div class="form-group row">
                            <label class="col-sm-12 col-md-2 col-form-label">Talent</label>
                            <div class="col-sm-12 col-md-10">
                                @Html.DropDownList("tid", null, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.tid, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-sm-12 col-md-2 col-form-label">Age Range</label>
                            <div class="col-sm-12 col-md-10">
                                @Html.EditorFor(model => model.agerange, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.agerange, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-sm-12 col-md-2 col-form-label">Gender</label>
                            <div class="col-sm-12 col-md-10">
                                @Html.EditorFor(model => model.gender, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.gender, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group row">
                            <label class="col-sm-12 col-md-2 col-form-label">Payment Range</label>
                            <div class="col-sm-12 col-md-10">
                                @Html.EditorFor(model => model.payrange, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.payrange, "", new { @class = "text-danger" })
                            </div>
                        </div>


                        <center>
                            <input type="submit" value="Submit" class=" btn btn-primary" />
                        </center>

                    }
                </div>
            </div>
        </div>
    </div>

    <!-- js -->
    <script src="~/vendors/scripts/core.js"></script>
    <script src="~/vendors/scripts/script.min.js"></script>
    <script src="~/vendors/scripts/process.js"></script>
    <script src="~/vendors/scripts/layout-settings.js"></script>
</body>
</html>


@*<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>eventrequire</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.pid, "pid", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("pid", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.pid, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.peid, "peid", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("peid", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.peid, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.tid, "tid", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("tid", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.tid, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.agerange, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.agerange, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.agerange, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.gender, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.gender, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.gender, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.payrange, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.payrange, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.payrange, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>*@

Views/EventRequire/Delete.cshtml
@model TalentHunt.Models.eventrequire

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>TalentHunt</title>
</head>
<body>
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>eventrequire</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.agerange)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.agerange)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.gender)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.gender)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.payrange)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.payrange)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.production.pname)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.production.pname)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.productionevent.ename)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.productionevent.ename)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.talent.ttype)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.talent.ttype)
            </dd>
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</body>
</html>

Views/EventRequire/Details.cshtml
@model TalentHunt.Models.eventrequire

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    <div>
        <h4>eventrequire</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.agerange)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.agerange)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.gender)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.gender)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.payrange)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.payrange)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.production.pname)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.production.pname)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.productionevent.ename)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.productionevent.ename)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.talent.ttype)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.talent.ttype)
            </dd>
    
        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.erid }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</body>
</html>

Views/EventRequire/Edit.cshtml
@model TalentHunt.ModelView.eventrequirev

@{
    Layout = null;
}

<!DOCTYPE html>



<html>
<head>
    <!-- Basic Page Info -->
    <meta charset="utf-8">
    <title>TalentHunt</title>

    <!-- Site favicon -->
    <link rel="apple-touch-icon" sizes="180x180" href="~/vendors/images/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="~/vendors/images/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="~/vendors/images/favicon-16x16.png">

    <!-- Mobile Specific Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap" rel="stylesheet">
    <!-- CSS -->
    <link rel="stylesheet" type="text/css" href="~/vendors/styles/core.css">
    <link rel="stylesheet" type="text/css" href="~/vendors/styles/icon-font.min.css">
    <link rel="stylesheet" type="text/css" href="~/vendors/styles/style.css">

    <!-- Favicon icon -->
    <link rel="icon" href="~/assets/images/favicon.svg" type="image/x-icon">
    <!-- fontawesome icon -->
    <link rel="stylesheet" href="~/assets/fonts/fontawesome/css/fontawesome-all.min.css">
    <!-- animation css -->
    <link rel="stylesheet" href="~/assets/plugins/animation/css/animate.min.css">

    <!-- vendor css -->
    <link rel="stylesheet" href="~/assets/css/style.css">


    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-119386393-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag() { dataLayer.push(arguments); }
        gtag('js', new Date());

        gtag('config', 'UA-119386393-1');
    </script>
</head>
<body>

    @{
        Html.RenderPartial("__Navbar");
    }

    <div class="main-container">
        <div class="pd-tr-20 xs-pd-10-10">
            <div class="min-height-200px">
                <!-- Default Basic Forms Start -->
                <div class="pd-20 card-box mb-30">
                    <div class="clearfix">
                        <div class="pull-left">
                            <h4 class="text-blue h4">Edit Event Requirements Info</h4>
                            <hr style="color:darkblue" />
                        </div>
                    </div>
                    @using (Html.BeginForm("Edit", "EventRequire", FormMethod.Post, new { enctype = "multipart/form-data" }))
                    {
                        @Html.AntiForgeryToken()

                        @Html.HiddenFor(model => model.erid)

                        <div class="form-group row">
                            <label class="col-sm-12 col-md-2 col-form-label">Age Range</label>
                            <div class="col-sm-12 col-md-10">
                                @Html.EditorFor(model => model.agerange, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.agerange, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group row">
                            <label class="col-sm-12 col-md-2 col-form-label">Gender</label>
                            <div class="col-sm-12 col-md-10">
                                @Html.EditorFor(model => model.gender, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.gender, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group row">
                            <label class="col-sm-12 col-md-2 col-form-label">Payment Range</label>
                            <div class="col-sm-12 col-md-10">
                                @Html.EditorFor(model => model.payrange, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.payrange, "", new { @class = "text-danger" })
                            </div>
                        </div>


                        @Html.HiddenFor(model => model.pid)
                        @Html.HiddenFor(model => model.peid)
                        @Html.HiddenFor(model => model.tid)

                        <center>
                            <input type="submit" value="Submit" class=" btn btn-primary" />
                        </center>

                    }
                </div>
            </div>
        </div>
    </div>

    <!-- js -->
    <script src="~/vendors/scripts/core.js"></script>
    <script src="~/vendors/scripts/script.min.js"></script>
    <script src="~/vendors/scripts/process.js"></script>
    <script src="~/vendors/scripts/layout-settings.js"></script>
</body>
</html>



@*<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>TalentHunt</title>
</head>
<body>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>eventrequire</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.erid)
    
            <div class="form-group">
                @Html.LabelFor(model => model.pid, "pid", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("pid", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.pid, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.peid, "peid", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("peid", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.peid, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.tid, "tid", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("tid", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.tid, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.agerange, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.agerange, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.agerange, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.gender, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.gender, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.gender, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.payrange, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.payrange, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.payrange, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>*@

Views/EventRequire/Index.cshtml
@model IEnumerable<TalentHunt.Models.eventrequire>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>TalentHunt</title>
</head>
<body>
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.agerange)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.gender)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.payrange)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.production.pname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.productionevent.ename)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.talent.ttype)
            </th>
            <th></th>
        </tr>
    
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.agerange)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.gender)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.payrange)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.production.pname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.productionevent.ename)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.talent.ttype)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.erid }) |
                @Html.ActionLink("Details", "Details", new { id=item.erid }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.erid })
            </td>
        </tr>
    }
    
    </table>
</body>
</html>