Models/talent.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TalentHunt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class talent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public talent()
        {
            this.eventrequires = new HashSet<eventrequire>();
            this.images = new HashSet<image>();
            this.userprofiles = new HashSet<userprofile>();
            this.videos = new HashSet<video>();
        }
    
        public int tid { get; set; }
        public string ttype { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eventrequire> eventrequires { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<image> images { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<userprofile> userprofiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<video> videos { get; set; }
    }
}

Controllers/TalentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TalentHunt.Models;
using TalentHunt.ModelView;

namespace TalentHunt.Controllers
{
    public class TalentController : Controller
    {
        private huntdbEntities1 db = new huntdbEntities1();

        // GET: Talent
        public ActionResult Index()
        {
            return View(db.talents.ToList());
        }

        [HttpPost]
        public ActionResult Index(string Search)
        {
            if (Session["aid"] != null)
            {
                if (Search == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                if (Search.ToLower() == "all" || Search == "")
                {
                    return View(db.talents.ToList());
                }
                List<talent> talent = db.talents.Where(p => p.ttype.Contains(Search) || Search == null).ToList();
                if (talent.Count() == 0)
                {
                    TempData["NotFound"] = "Data Not Found";
                }

                return View(talent.ToList());
            }
            else
            {
                return RedirectToAction("Login", "AdminLogin");
            }
        }

        // GET: Talent/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            talent talent = db.talents.Find(id);
            if (talent == null)
            {
                return HttpNotFound();
            }
            return View(talent);
        }

        // GET: Talent/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Talent/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "tid,ttype")] talentv talentv)
        {
            if (Session["aid"] != null)
            {
                if (ModelState.IsValid)
                {
                    List<talent> talent = db.talents.Where(p => p.ttype == talentv.ttype).ToList();
                    if (talent.Count() == 0)
                    {
                        talent talent1 = new talent();
                        AutoMapper.Mapper.Map(talentv, talent1);

                        db.talents.Add(talent1);
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                    TempData["AlreadyExists"] = "Talent Already Exists";
                }

                return View(talentv);
            }
            else
            {
                return RedirectToAction("Login", "AdminLogin");
            }
        }

        // GET: Talent/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            talent talent = db.talents.Find(id);
            talentv talentv = new talentv();
            AutoMapper.Mapper.Map(talent, talentv);
            if (talent == null)
            {
                return HttpNotFound();
            }
            return View(talentv);
        }

        // POST: Talent/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "tid,ttype")] talentv talentv)
        {
            if (Session["aid"] != null)
            {
                if (ModelState.IsValid)
                {
                    talent talent = new talent();
                    AutoMapper.Mapper.Map(talentv, talent);

                    db.Entry(talent).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                return View(talentv);
            }
            else
            {
                return RedirectToAction("Login", "AdminLogin");
            }
        }

        // GET: Talent/Delete/5
        public ActionResult Delete(int? id)
        {
            if (Session["aid"] != null)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                talent talent= db.talents.Find(id);
                if (talent != null)
                {
                    db.talents.Remove(talent);
                    try
                    {
                        db.SaveChanges();
                    }
                    catch (Exception e)
                    {
                        TempData["talenterr"] = "Talent cannot be deleted because users are available with this talent";
                    }
                    return RedirectToAction("Index");
                }
                else
                {
                    return HttpNotFound();
                }
            }
            else
            {
                return RedirectToAction("Login", "AdminLogin");
            }
        }

        // POST: Talent/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            talent talent = db.talents.Find(id);
            db.talents.Remove(talent);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Talent/Create.cshtml
@model TalentHunt.ModelView.talentv

@{
    ViewBag.Title = "Create";
    Layout = null;
}

<html>
<head>
    <!-- Basic Page Info -->
    <meta charset="utf-8">
    <title>TalentHunt</title>

    <!-- Site favicon -->
    <link rel="apple-touch-icon" sizes="180x180" href="~/vendors/images/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="~/vendors/images/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="~/vendors/images/favicon-16x16.png">

    <!-- Mobile Specific Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap" rel="stylesheet">
    <!-- CSS -->
    <link rel="stylesheet" type="text/css" href="~/vendors/styles/core.css">
    <link rel="stylesheet" type="text/css" href="~/vendors/styles/icon-font.min.css">
    <link rel="stylesheet" type="text/css" href="~/vendors/styles/style.css">


    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-119386393-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag() { dataLayer.push(arguments); }
        gtag('js', new Date());

        gtag('config', 'UA-119386393-1');
    </script>
</head>
<body>

    @{
        Html.RenderPartial("_Header");
        Html.RenderPartial("_Leftbar");
    }
    <div class="mobile-menu-overlay"></div>

    <div class="main-container-2">
        <div class="pd-ltr-20 xs-pd-20-10">
            <div class="min-height-200px">

                <!-- Default Basic Forms Start -->
                <div class="pd-20 card-box mb-30">
                    <div class="clearfix">
                        <div class="pull-left">
                            <h4 class="text-blue h4">Add Talent</h4>
                        </div>
                    </div>
                    @using (Html.BeginForm(FormMethod.Post))
                    {
                        @Html.AntiForgeryToken()
                        <div class="form-group row">
                            <label class="col-sm-12 col-md-2 col-form-label">Talent Type</label>
                            <div class="col-sm-12 col-md-10">
                                @Html.EditorFor(model => model.ttype, new { htmlAttributes = new { @name = "type", @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.ttype, "", new { @class = "text-danger" })
                                <span class="text-danger">@TempData["AlreadyExists"]</span>
                            </div>
                        </div>

                        <div class="mb-0 d-flex justify-content-center ">
                            <input type="submit" value="Add" class="btn btn-primary" />
                            @Html.ActionLink("View Talent", "Index", "Talent", new { @area = "" }, new { @class = "btn btn-primary mx-5" })
                        </div>


                    }
                </div>



            </div>
        </div>
        <!-- Default Basic Forms End -->

    </div>

    <!-- js -->
    <script src="~/vendors/scripts/core.js"></script>
    <script src="~/vendors/scripts/script.min.js"></script>
    <script src="~/vendors/scripts/process.js"></script>
    <script src="~/vendors/scripts/layout-settings.js"></script>
</body>
</html>

Views/Talent/Delete.cshtml
@model TalentHunt.Models.talent

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>talent</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ttype)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ttype)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/Talent/Details.cshtml
@model TalentHunt.Models.talent

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>talent</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ttype)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ttype)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.tid }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Talent/Edit.cshtml
@model TalentHunt.ModelView.talentv

@{
    ViewBag.Title = "Edit";
    Layout = null;
}

<html>
<head>
    <!-- Basic Page Info -->
    <meta charset="utf-8">
    <title>TalentHunt</title>

    <!-- Site favicon -->
    <link rel="apple-touch-icon" sizes="180x180" href="~/vendors/images/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="~/vendors/images/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="~/vendors/images/favicon-16x16.png">

    <!-- Mobile Specific Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap" rel="stylesheet">
    <!-- CSS -->
    <link rel="stylesheet" type="text/css" href="~/vendors/styles/core.css">
    <link rel="stylesheet" type="text/css" href="~/vendors/styles/icon-font.min.css">
    <link rel="stylesheet" type="text/css" href="~/vendors/styles/style.css">


    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-119386393-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag() { dataLayer.push(arguments); }
        gtag('js', new Date());

        gtag('config', 'UA-119386393-1');
    </script>
</head>
<body>

    @{
        Html.RenderPartial("_Header");
        Html.RenderPartial("_Leftbar");
    }
    <div class="mobile-menu-overlay"></div>

    <div class="main-container-2">
        <div class="pd-ltr-20 xs-pd-20-10">
            <div class="min-height-200px">

                <!-- Default Basic Forms Start -->
                <div class="pd-20 card-box mb-30">
                    <div class="clearfix">
                        <div class="pull-left">
                            <h4 class="text-blue h4">Edit Talent</h4>
                        </div>
                    </div>
                    @using (Html.BeginForm(FormMethod.Post))
                    {
                        @Html.AntiForgeryToken()
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.tid)

                        <div class="form-group row">
                            <label class="col-sm-12 col-md-2 col-form-label">Talent Type</label>
                            <div class="col-sm-12 col-md-10">
                                @Html.EditorFor(model => model.ttype, new { htmlAttributes = new { @class = "form-control" } })
                            </div>
                        </div>
                        <div class="mb-0 d-flex justify-content-center ">
                            <input type="submit" value="Save" class="btn btn-primary" />
                        </div>


                    }
                </div>



            </div>
        </div>
        <!-- Default Basic Forms End -->

    </div>

    <!-- js -->
    <script src="~/vendors/scripts/core.js"></script>
    <script src="~/vendors/scripts/script.min.js"></script>
    <script src="~/vendors/scripts/process.js"></script>
    <script src="~/vendors/scripts/layout-settings.js"></script>
</body>
</html>

Views/Talent/Index.cshtml
@model IEnumerable<TalentHunt.Models.talent>

@{
    ViewBag.Title = "Index";
    Layout = null;

    var count = 0;

    foreach (var item in Model)
    {
        count++;
    }
}

<html>
<head>
    <!-- Basic Page Info -->
    <meta charset="utf-8">
    <title>TalentHunt</title>

    <!-- Site favicon -->
    <link rel="apple-touch-icon" sizes="180x180" href="~/vendors/images/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="~/vendors/images/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="~/vendors/images/favicon-16x16.png">

    <!-- Mobile Specific Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap" rel="stylesheet">
    <!-- CSS -->
    <link rel="stylesheet" type="text/css" href="~/vendors/styles/core.css">
    <link rel="stylesheet" type="text/css" href="~/vendors/styles/icon-font.min.css">
    <link rel="stylesheet" type="text/css" href="~/vendors/styles/style.css">
</head>
<body>

    @{
        Html.RenderPartial("_Header");
        Html.RenderPartial("_Leftbar");
    }
    <div class="mobile-menu-overlay"></div>

    <div class="main-container-2">
        <div class="pd-ltr-20 xs-pd-20-10">
            <div class="min-height-200px">

                <!-- Default Basic Forms Start -->

                <div class="pd-20 card-box mb-30">
                    <div class="clearfix mb-20">

                        <div class="pull-left">
                            <h4 class="text-blue h4"> Talents <span class="text-black-50 mx-3">(Total - @count)</span> </h4>
                        </div>

                        @using (Html.BeginForm(FormMethod.Post))
                        {
                            <div class="pull-left">
                            @Html.TextBox("Search", "", new { @class = "form-control" , placeholder = "Enter Talent" })
                            </div>
                            <div class="pull-left mx-2">
                             <input type="submit" class="btn btn-outline-primary" value="Search" name="submit" />
                             </div>
                         }
                        <div class="pull-right">
                            <h4 class="text-blue h4">@Html.ActionLink("Create New", "Create", "Talent", new { @class = "btn btn-outline-primary" })</h4>
                        </div>

                    </div>

                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">Talent</th>
                                <th scope="col">Actions</th>

                            </tr>
                        </thead>
                        <tbody>
                            <span class="text-danger">@TempData["NotFound"]</span>
                            <span class="text-danger">@TempData["talenterr"]</span>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@Html.DisplayFor(modelItem => item.ttype)</td>
                                    <td>
                                        @Html.ActionLink("Edit", "Edit", new { id = item.tid }) |
                                        @Html.ActionLink("Delete", "Delete", new { id = item.tid }, new { onclick = $"return confirm('Are you sure you want to delete {item.ttype} talent?')" })
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

    </div>

    <!-- js -->
    <script src="~/vendors/scripts/core.js"></script>
    <script src="~/vendors/scripts/script.min.js"></script>
    <script src="~/vendors/scripts/process.js"></script>
    <script src="~/vendors/scripts/layout-settings.js"></script>
</body>
</html>